export const noImage = "images/no_image.jpg";

export const solarSystem = [
    {
        type:'planet',
        name:'Меркурий',
        image:'https://upload.wikimedia.org/wikipedia/commons/d/d9/Mercury_in_color_-_Prockter07-edit1.jpg',
        smAxis:'57909227',
        aRadius:'2439.7',
        mass:{
            wholePart:'3.33022',
            degree:'23'
        },
        temp:'от -190 до +430'
    },
    {
        type:'planet',
        name:'Венера',
        image:'https://upload.wikimedia.org/wikipedia/commons/f/ff/PIA23791-Venus-RealAndEnhancedContrastViews-20200608_%28cropped2%29.jpg',
        smAxis:'108208930',
        aRadius:'6051.8',
        mass:{
            wholePart:'4.8675',
            degree:'24'
        },
        temp:'+464'
    },
    {
        type:'planet',
        name:'Земля',
        image:'https://upload.wikimedia.org/wikipedia/commons/9/97/The_Earth_seen_from_Apollo_17.jpg',
        smAxis:'149598261',
        aRadius:'6371',
        mass:{
            wholePart:'5.9726',
            degree:'24'
        },
        temp:'от -89,2 до +56,7'
    },
    {
        type:'planet',
        name:'Марс',
        image:'https://upload.wikimedia.org/wikipedia/commons/0/02/OSIRIS_Mars_true_color.jpg',
        smAxis:'227943820',
        aRadius:'3389.5',
        mass:{
            wholePart:'6.4171',
            degree:'23'
        },
        temp:'от -153 до +35'
    },
    {
        type:'planet',
        name:'Юпитер',
        image:'https://upload.wikimedia.org/wikipedia/commons/2/2b/Jupiter_and_its_shrunken_Great_Red_Spot.jpg',
        smAxis:'778547200',
        aRadius:'69911',
        mass:{
            wholePart:'1.8986',
            degree:'27'
        },
        temp:'-145'
    },
    {
        type:'planet',
        name:'Сатурн',
        image:'https://upload.wikimedia.org/wikipedia/commons/1/13/Saturn_during_Equinox_%28rot45%29.jpg',
        smAxis:'1429394069',
        aRadius:'58232',
        mass:{
            wholePart:'5.6846',
            degree:'26'
        },
        temp:'-140'
    },
    {
        type:'planet',
        name:'Уран',
        image:'https://upload.wikimedia.org/wikipedia/commons/3/3d/Uranus2.jpg',
        smAxis:'2876679082',
        aRadius:'25367',
        mass:{
            wholePart:'8.6813',
            degree:'25'
        },
        temp:'-197'
    },
    {
        type:'planet',
        name:'Нептун',
        image:'https://upload.wikimedia.org/wikipedia/commons/6/63/Neptune_-_Voyager_2_%2829347980845%29_flatten_crop.jpg',
        smAxis:'4503443661',
        aRadius:'24622',
        mass:{
            wholePart:'1.0243',
            degree:'26'
        },
        temp:'-201'
    },
    {
        type:'dwarfPlanet',
        name:'Церера',
        image:'https://upload.wikimedia.org/wikipedia/commons/e/e9/Ceresintruecolor.png',
        smAxis:'413767000',
        aRadius:'463.5',
        mass:{
            wholePart:'9.393',
            degree:'20'
        },
        temp:'-106'
    },
    {
        type:'dwarfPlanet',
        name:'Плутон',
        image:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Pluto_in_True_Color_-_High-Res.jpg/2048px-Pluto_in_True_Color_-_High-Res.jpg',
        smAxis:'5906440633',
        aRadius:'1188.3',
        mass:{
            wholePart:'1.303',
            degree:'22'
        },
        temp:'-223'
    },
    {
        type:'dwarfPlanet',
        name:'Хаумеа',
        image:'https://upload.wikimedia.org/wikipedia/commons/9/90/2003EL61art.jpg',
        smAxis:'6475654996',
        aRadius:'816',
        mass:{
            wholePart:'4.006',
            degree:'21'
        },
        temp:'-223'
    },
    {
        type:'dwarfPlanet',
        name:'Макемаке',
        image:'https://upload.wikimedia.org/wikipedia/commons/3/34/Makemake_with_moon.JPG',
        smAxis:'6797173881',
        aRadius:'739',
        mass:{
            wholePart:'3',
            degree:'21'
        },
        temp:'-243'
    },
    {
        type:'dwarfPlanet',
        name:'Эрида',
        image:'https://upload.wikimedia.org/wikipedia/commons/5/5b/Eris_and_dysnomia2.jpg',
        smAxis:'10139893273',
        aRadius:'1163',
        mass:{
            wholePart:'1,67',
            degree:'22'
        },
        temp:'-253'
    }
]
